# Generated by Django 6.1.1 on 2026-09-05 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_alter_category_options_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='short_dexscription',
            new_name='short_description',
        ),
    ]
