# Generated by Django 6.1.1 on 2026-09-05 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0005_alter_blog_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[(0, 'Draft'), (1, 'Published')], default=0, max_length=20),
        ),
    ]
